language: rust

rust:
  - stable
  - beta
  - nightly
env:
  - FEATURES=unsafe_internals
  - FEATURES=reverse_bits
  - FEATURES=reverse_bits unsafe_internals

matrix:
  # Exclude combinations with unstable features for stable and beta
  exclude:
    - rust: stable
    - rust: beta
  include:
    - rust: nightly
      env: FEATURES=''
    - rust: stable
      env: FEATURES=''
    - rust: beta
      env: FEATURES=''

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo build --tests --features "$FEATURES"
  - cargo test --features "$FEATURES"
  - "[ \"$TRAVIS_RUST_VERSION\" != 'nightly' ] ||  cargo bench --features \"$FEATURES\""
  - "[ \"$TRAVIS_RUST_VERSION\" != 'nightly' ] ||  cargo fmt -- --check"

cache: cargo
